openapi: 3.0.0
info:
  title: 2팀-How Do I Look
  version: 1.0.1
  description: 이 프로젝트는 코드잇 Node.js 스프린트의 초급 팀 프로젝트 진행한 프로젝트입니다.
servers:
  - url: "http://localhost:3000"

tags:
  - name: Style
    description: 상의, 하의, 신발, 악세사리 등 아웃핏들을 모은 스타일 게시글
  - name: Curation
    description: 스타일 게시글에 대한 평가
  - name: Comment
    description: 큐레이션에 대한 스타일 작성자의 댓글

paths:
  /styles:
    $ref: "./paths/stylePaths.yaml"

components:
  schemas:
    $ref: "./schemas/_index.yaml"
  parameters:
    $ref: "./parameters/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
